### ISSUE TITLE
Criar Páginas de Pós-Registro e Perfil Web

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/SD.Code-Trouble.Documentation#6]
### **Contexto**  
O time de design deverá criar as páginas de **Pós-Registro** e **Perfil** para a versão web. Essas páginas devem seguir o style guide, estar bem estruturadas e atender às boas práticas de design e acessibilidade.

### **História do Usuário**  
Como um usuário recém-registrado,  
Quero acessar as páginas de pós-registro e meu perfil,  
Para personalizar minhas informações e continuar minha jornada no produto.

---

## **Critérios de Aceite**

- **Dado** que o design das páginas foi concluído,  
  **Quando** revisado pelo time,  
  **Então** estará alinhado ao style guide e pronto para desenvolvimento.

- **Dado** que o layout foi criado,  
  **Quando** validado em diferentes resoluções web,  
  **Então** será responsivo e acessível.

---

## **Tarefas**

1. Criar layout da página de **Pós-Registro**.
   - [ ] Incluir componentes atualizados e responsivos.
   - [ ] Validar integração com o fluxo de onboarding.

2. Criar layout da página de **Perfil**.
   - [ ] Estruturar as seções (e.g., informações pessoais, preferências).
   - [x] Garantir acessibilidade em todos os elementos interativos.

3. Validar o design final com o time.
   - [x] Testar consistência visual com outros designs web.
   - [ ] Ajustar feedback recebido.

---

**Comment by arthurzop** [comment]
Ambas páginas finalizadas.

Profile Page: 
Projetada inicialmente para a entrega do MVP. Conforme implementamos detalhes ao website, é possível adicionar mais _features_ a essa página, como badges, troféus, etc. 

OnBoarding Page:
Finalizada e completa. Porém é diretamente atrelada à Profile Page, sendo assim, conforme adicionamos mais _features_ ao perfil é ideal sempre revisitar essa página, para manter a coerência entre as duas.
