### ISSUE TITLE
Criar SplashScreen Web e Mobile

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/SD.Code-Trouble.Documentation#7]
### **Contexto**  
O time de design deverá criar uma **SplashScreen** para as versões web e mobile, garantindo que seja visualmente atraente, siga o style guide e reflita a identidade visual da Code Trouble.

### **História do Usuário**  
Como um usuário,  
Quero visualizar uma SplashScreen ao abrir o aplicativo ou site,  
Para ter uma experiência visual agradável enquanto o conteúdo carrega.

---

## **Critérios de Aceite**

- **Dado** que a SplashScreen foi criada,  
  **Quando** revisada,  
  **Então** estará alinhada ao style guide e pronta para implementação.

- **Dado** que o design foi validado,  
  **Quando** revisado em dispositivos web e mobile,  
  **Então** será responsivo e adequado para ambas as plataformas.

---

## **Tarefas**

1. Criar layout da **SplashScreen Web**.
   - [ ] Incluir logo, animações e elementos visuais.  
   - [ ] Validar tempo e transição da tela inicial.  

2. Criar layout da **SplashScreen Mobile**.
   - [ ] Garantir adaptação ao tamanho de telas mobile.  
   - [ ] Validar interatividade e animações.  

3. Testar e validar os designs.
   - [ ] Obter feedback do time e ajustar.  

---

**Comment by arthurzop** [comment]
**Splash Screen para App finalizada.**

Para visualização: Deixei os frames junto do _breakdown_ da animação na página 'Prototipação Mobile', no figma da Code Trouble.

- _Breakdown_: Explicando como funciona e como rodar a animação para visualização.

**Defesa de ideia:** 

> Por que não animar a escrita das chaves da logo?

Não implementei a escrita das chaves como as das letras por dois motivos:

1. Para manter a logo presente a todo momento: 
Se animasse até as chaves, o primeiro elemento que o usuário veria seria apenas a chave esquerda, assim não passando diretamente a marca. Do jeito que fiz mantive a marca sempre presente, iniciando com a logo compacta ( {c} ), e finalizando com a logo completa ( {code} trouble ).

2. Para manter a animação mais curta e mais direta:
Adicionar mais passos e frames à animação poderia estender excessivamente o tempo, até além do carregamento da aplicação.

**Comment by arthurzop** [comment]
Ainda tenho que fazer estudo sobre isso, no mobile sei que dá pra suar vídeo/mídia. Para web ainda não fiz.
